exostest/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.core.urlresolvers import RegexURLResolver

def lookup_root(urlconf):
    urlconf_module, app_name, namespace = include(urlconf)
    resolver = RegexURLResolver('^', urlconf_module, app_name=app_name, namespace=namespace)
    return resolver.resolve('').func

urlpatterns = [
    url(r'^$', lookup_root('users.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^admin/', admin.site.urls),
]

users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<user_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^edit/(?P<user_id>[0-9]+)/$', views.edit, name='edit'),
    url(r'^delete/(?P<user_id>[0-9]+)/$', views.delete, name='delete'),
    url(r'^new/$', views.new, name='new'),
    url(r'^export/$', views.export, name='export'),
]

users/models.py
from django.db import models
from django.utils.dateparse import datetime
from django.core.validators import MaxValueValidator, MinValueValidator
import random
# Create your models here.

def random_integer():
    return random.randint(1, 100)

class User(models.Model):
    username = models.CharField(max_length=50)
    birthday = models.DateField(default=datetime.datetime.now)
    random_number = models.SmallIntegerField(default=random_integer, validators=[MaxValueValidator(100), MinValueValidator(1)])

users/forms.py
from django.forms import ModelForm
from .models import User

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'birthday', 'random_number']

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template import loader
from django.http import HttpResponse
from django.utils.dateparse import datetime
from .models import User
from .forms import UserForm
import csv

def bizzfuzz(random_number):
    result = random_number
    if random_number % 3 == 0:
        result = "Bizz"
    if random_number % 5 == 0:
        result = "Fuzz"
    if random_number % 15 == 0:
        result = "BizzFuzz"
    return result

def validate_user(birthday):
    now = datetime.datetime.now()
    birth_year = birthday.year
    age = now.year - birth_year
    if (age > 13):
        result = "allowed"
    else:
        result = "blocked"
    return result

def index(request):
    user_list = User.objects.all()
    template = loader.get_template('index.html')
    context = {
        'user_list': user_list
    }
    return HttpResponse(template.render(context, request))

def detail(request, user_id):
    user = User.objects.get(pk=user_id)
    return render(request, 'detail.html', {'user': user})

def delete(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    user.delete()
    return redirect('users:index')

def edit(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    if request.method == "POST":
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            return redirect('users:index')
        else:
            return render(request, 'edit.html', {'form': form})
    else:
        form = UserForm(instance=user)
        return render(request, 'edit.html', {'form': form})

def new(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            return redirect('users:index')
        else:
            return render(request, 'new.html', {'form': form})
    else:
        form = UserForm()
        return render(request, 'new.html', {'form': form})

def export(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="export.csv"'
    writer = csv.writer(response)
    writer.writerow(['Username', 'Birthday', 'Eligible', 'Random Number', 'BizzFuzz'])
    user_list = User.objects.all()
    for user in user_list:
        writer.writerow([user.username, user.birthday, validate_user(user.birthday), user.random_number, bizzfuzz(user.random_number)])
    return response

users/templates/detail.html
{% load bizzfuzz %}
{% load validate_user %}
<h1>User Detail</h1>
<table border="1" cellspacing="0">
  <tr>
    <td>Username</td>
    <td>{{user.username}}</td>
  </tr>
  <tr>
    <td>Birthday</td>
    <td>{{user.birthday}}</td>
  </tr>
  <tr>
    <td>Eligible</td>
    <td>{% validate_user user.birthday %}</td>
  </tr>
  <tr>
    <td>Random Number</td>
    <td>{{user.random_number}}</td>
  </tr>
  <tr>
    <td>BizzFuzz</td>
    <td>{% bizzfuzz user.random_number %}</td>
  </tr>
</table>

users/templates/edit.html
<h1>User Edit</h1>
<a href="{% url 'users:index' %}"><- Back</a>
<form method="post">
{% csrf_token %}
<table border="1" cellspacing="0">
{{ form }}
<tr><td colspan="2" align="right"><input type="submit" value="Save" /></td></tr>
</table>
</form>

users/templates/index.html
{% load bizzfuzz %}
{% load validate_user %}
<a href="{% url 'users:new' %}">New User</a> | <a href="{% url 'users:export' %}">Export to csv</a>
<br/>

{% if user_list %}
<table border="1" cellspacing="0">
  <tr>
    <th>Username</th>
    <th>Birthday</th>
    <th>Eligible</th>
    <th>Random Number</th>
    <th>BizzFuzz</th>
    <th>Action</th>
  </tr>
    {% for user in user_list %}
        <tr>
          <td><a href="{% url 'users:detail' user.id %}">{{user.username}}</a></td>
          <td>{{user.birthday}}</td>
          <td>{% validate_user user.birthday %}</td>
          <td>{{user.random_number}}</td>
          <td>{% bizzfuzz user.random_number %}</td>
          <td><a href="{% url 'users:edit' user.id %}">Edit</a> | <a href="{% url 'users:delete' user.id %}">Delete</a></td>
        </tr>
    {% endfor %}
</table>
{% else %}
    <p>No users are available.</p>
{% endif %}

users/templates/new.html
<h1>New User</h1>
<a href="{% url 'users:index' %}"><- Back</a>
<form method="post">
{% csrf_token %}
<table border="1" cellspacing="0">
{{ form }}
<tr><td colspan="2" align="right"><input type="submit" value="Create" /></td></tr>
</table>
</form>